# Generated by Django 2.2.10 on 2020-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsprojectspage',
            old_name='h_two_eda',
            new_name='h_two',
        ),
        migrations.AlterField(
            model_name='dsprojectspage',
            name='eda',
            field=models.TextField(blank=True),
        ),
    ]
