# Generated by Django 2.2.10 on 2020-02-23 14:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('projects', '0002_auto_20200223_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsProjectsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('h_one', models.CharField(default='Project Name', max_length=250)),
                ('problem_statement', wagtail.core.fields.RichTextField(blank=True)),
                ('img_alt', models.CharField(default='Image Alt Text', max_length=250)),
                ('h_two_eda', models.CharField(default='Project Name', max_length=250)),
                ('eda_description', models.TextField(blank=True)),
                ('model_description', wagtail.core.fields.RichTextField(blank=True)),
                ('canonical', models.URLField(default='Canonical URL')),
                ('ds_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='DsProjects',
        ),
    ]
