# Generated by Django 2.2.10 on 2020-02-23 01:29

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200223_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsprojectspage',
            name='h_two_eda',
        ),
        migrations.AddField(
            model_name='dsprojectspage',
            name='data_review',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
