# Generated by Django 2.2.10 on 2020-02-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200226_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsprojectspage',
            old_name='eda',
            new_name='eda_section_one',
        ),
        migrations.AddField(
            model_name='dsprojectspage',
            name='eda_section_three',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dsprojectspage',
            name='eda_section_two',
            field=models.TextField(blank=True),
        ),
    ]
