# Generated by Django 2.2.10 on 2020-02-23 01:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200223_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsprojectspage',
            name='model_conclusion',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='dsprojectspage',
            name='model_results',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
