# Generated by Django 2.2.10 on 2020-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_dsprojectspage_model_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsprojectspage',
            name='model_conclusion',
            field=models.TextField(blank=True),
        ),
    ]
