# Generated by Django 2.2.10 on 2020-02-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_dsprojectspage_model_conclusion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsprojectspage',
            old_name='eda_description',
            new_name='data_summary',
        ),
    ]
