# Generated by Django 2.2.10 on 2020-02-24 21:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200224_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsprojectspage',
            name='eda',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
